# Generated by Django 6.1 on 2026-09-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
