# Generated by Django 6.1 on 2026-09-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_serviceprovider_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
