# Generated by Django 6.1 on 2026-09-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_create_at'),
        ('cource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentno',
            name='paid',
            field=models.CharField(blank=True, default='unpaid', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentno',
            unique_together={('user', 'cource')},
        ),
    ]
