# Generated by Django 6.1 on 2026-09-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_application_applied_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
