# Generated by Django 6.1 on 2026-09-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_application_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
